# Generated by Django 5.2.7 on 2025-11-11 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interview_jobpost_organizationdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='job',
            name='org',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_url',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.application'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobpost'),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
