# Generated by Django 5.2.7 on 2025-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_candidate_remove_job_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
