# Generated by Django 5.1.2 on 2026-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='AI-calculated similarity score between CV and job description (0-1)', null=True),
        ),
    ]
