# Generated by Django 5.1.2 on 2026-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.CharField(blank=True, help_text='Auto-generated unique interview link when similarity score >= 50%', max_length=255, null=True),
        ),
    ]
